### ISSUE TITLE
Repetition

### ISSUE THREAD

**Issue by cartfisk** [sshah37/COMP330-TwitterParser#2]
I noticed your code has a lot of repetition in things that could be extrapolated to methods, moved to new classes etc. If you include a bit more abstraction I think your code would be easier to maintain and easier to debug. Right now it looks like if you decide to change one thing you'd have to comb through all your code and change a whole bunch of other things to get the behavior consistent across the project.

**Comment by aviatoali** [comment]
Thanks for your comments. Yeah, looking back at it now it seems all mashed together and filled with redundancies. I'm in the process of pulling out the functionality over some abstract classes and interfaces in the hopes of making the bulk of the storage/processing/recognition very general so that the twitter-specific instances can have trimmer, more precise methods.
